giveBoosterNameMenuTitle: '&aType booster name'
giveBoosterDisplayNameMenuTitle: '&aType booster displayName'
giveBoosterDurationMenuTitle: '&aType booster duration'
giveBoosterMultiplierMenuTitle: '&aType booster multiplier'

messages:
  invalidBoosterMultiplier: '&cCan not create booster, multiplier is invalid'
  createdBooster: '&aYou have created booster'
  invalidBoosterDuration: '&cDuration is invalid, e.g. 12h'
  playerOffline: '&cThis player is offline'
  boosterDoesNotExist: '&cThis booster does not exist'
  givenBooster: '&aYou have given a booster to {PLAYER_NAME}'
  userDoesNotExist: '&cThis user does not exist'
  givenBoosterEveryone: '&aYou have given a booster to everyone'
  boosters: '&aBoosters'
  haveThisBooster: '&cThis user has this booster'
  boosterExpired: '&aYour booster with name {BOOSTER_DISPLAY_NAME} &ahas been expired'
  boosterAlreadyExists: '&cThis booster already exists'
  playerHelp:
    - '&7/&a{player_command} booster help &7- All booster commands'
    - '&7/&a{player_command} booster list &7- List of your boosters'
  adminHelp:
    - '&7/&a{admin_command} booster create &7- Opens GUI to creation boosters'
    - '&7/&a{admin_command} booster help &7- All booster commands'
    - '&7/&a{admin_command} booster give <global|player_name> <booster_name> &7- Gives booster to everyone or someone'
    - '&7/&a{admin_command} booster list &7- List of all boosters'